export const types = {
	//SYNC
	AUTHENTICATE: 'AUTHENTICATE',
	INITIALIZE: 'INITIALIZE',

	//ASYNC
	SIGNUP_ASYNC: 'SIGNUP_ASYNC',
	LOGIN_ASYNC: 'LOGIN_ASYNC',
	AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
	INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',

};